### ISSUE TITLE
why the input horizon is not equal to the output horizon ?

### ISSUE THREAD

**Issue by yygbruce** [TinyMPC/tinympc-python#4]
sorry, i have solved it! Compared with Casadi, it is indeed much faster.

**Comment by xkhainguyen** [comment]
Hi, if possible, could you share how you fixed it? That'd be valuable for future references. 

Many thanks.

**Comment by yygbruce** [comment]
Hi, @xkhainguyen !I just convert nonlinear relationships into linear relationships.But, I have not yet implemented nonlinearity in tinympc.
Finally, I have a question: the input horizon is not equal to the output horizon?
